=== camenduru/lumina-next-compositional-tost/schema.json
{
  "$schema": "http://json-schema.org/draft-04/hyper-schema#",
  "type": "object",
  "properties": {
    "readme": {
      "type": "string",
      "title": "Lumina-T2X: Transforming Text into Any Modality, Resolution, and Duration via Flow-based Large Diffusion Transformers",
      "author": "Peng Gao, Le Zhuo, Dongyang Liu, Ruoyi Du, Xu Luo, Longtian Qiu, Yuhang Zhang, Chen Lin, Rongjie Huang, Shijie Geng, Renrui Zhang, Junlin Xi, Wenqi Shao, Zhengkai Jiang, Tianshuo Yang, Weicai Ye, He Tong, Jingwen He, Yu Qiao, Hongsheng Li",
      "code": "https://github.com/Alpha-VLLM/Lumina-T2X",
      "paper": "https://arxiv.org/abs/2405.05945",
      "tags": [
        "Text to Image"
      ],
      "widget": "readme"
    },
    "cap1": {
      "type": "string",
      "description": "Prompt 1",
      "widget": "textarea"
    },
    "cap2": {
      "type": "string",
      "description": "Prompt 2",
      "widget": "textarea"
    },
    "cap3": {
      "type": "string",
      "description": "Prompt 3",
      "widget": "textarea"
    },
    "cap4": {
      "type": "string",
      "description": "Prompt 4",
      "widget": "textarea"
    },
    "neg_cap": {
      "type": "string",
      "description": "Negative Prompt",
      "widget": "textarea"
    },
    "resolution": {
      "type": "string",
      "widget": "select",
      "description": "Resolution",
      "oneOf": [
        {
          "description": "2048x1024 (4x1 Grids)",
          "enum": [
            "2048x1024 (4x1 Grids)"
          ]
        },
        {
          "description": "2560x1024 (4x1 Grids)",
          "enum": [
            "2560x1024 (4x1 Grids)"
          ]
        },
        {
          "description": "3072x1024 (4x1 Grids)",
          "enum": [
            "3072x1024 (4x1 Grids)"
          ]
        },
        {
          "description": "1024x1024 (2x2 Grids)",
          "enum": [
            "1024x1024 (2x2 Grids)"
          ]
        },
        {
          "description": "1536x1536 (2x2 Grids)",
          "enum": [
            "1536x1536 (2x2 Grids)"
          ]
        },
        {
          "description": "2048x2048 (2x2 Grids)",
          "enum": [
            "2048x2048 (2x2 Grids)"
          ]
        },
        {
          "description": "1024x2048 (1x4 Grids)",
          "enum": [
            "1024x2048 (1x4 Grids)"
          ]
        },
        {
          "description": "1024x2560 (1x4 Grids)",
          "enum": [
            "1024x2560 (1x4 Grids)"
          ]
        },
        {
          "description": "1024x3072 (1x4 Grids)",
          "enum": [
            "1024x3072 (1x4 Grids)"
          ]
        }
      ],
      "default": "2048x1024 (4x1 Grids)"
    },
    "num_sampling_steps": {
      "type": "integer",
      "description": "Num Sampling Steps"
    },
    "cfg_scale": {
      "type": "number",
      "description": "CFG Scale"
    },
    "solver": {
      "type": "string",
      "widget": "select",
      "description": "Solver",
      "oneOf": [
        {
          "description": "euler",
          "enum": [
            "euler"
          ]
        },
        {
          "description": "midpoint",
          "enum": [
            "midpoint"
          ]
        },
        {
          "description": "rk4",
          "enum": [
            "rk4"
          ]
        }
      ],
      "default": "midpoint"
    },
    "t_shift": {
      "type": "number",
      "description": "Time Shift"
    },
    "seed": {
      "type": "number",
      "description": "Seed (0 = random)"
    },
    "scaling_method": {
      "type": "string",
      "widget": "select",
      "description": "Scaling Method",
      "oneOf": [
        {
          "description": "Time-aware",
          "enum": [
            "Time-aware"
          ]
        },
        {
          "description": "None",
          "enum": [
            "None"
          ]
        }
      ],
      "default": "Time-aware"
    },
    "scaling_watershed": {
      "type": "number",
      "description": "Scaling Watershed"
    },
    "proportional_attn": {
      "type": "boolean",
      "description": "Scaling Watershed"
    },
    "width_2048": {
      "type": "integer",
      "readOnly": "true",
      "description": "Width",
      "visibleIf": {
        "/resolution": [
          "2048x1024 (4x1 Grids)",
          "2048x2048 (2x2 Grids)"
        ]
      }
    },
    "width_2560": {
      "type": "integer",
      "readOnly": "true",
      "description": "Width",
      "visibleIf": {
        "/resolution": [
          "2560x1024 (4x1 Grids)"
        ]
      }
    },
    "width_3072": {
      "type": "integer",
      "readOnly": "true",
      "description": "Width",
      "visibleIf": {
        "/resolution": [
          "3072x1024 (4x1 Grids)"
        ]
      }
    },
    "width_1024": {
      "type": "integer",
      "readOnly": "true",
      "description": "Width",
      "visibleIf": {
        "/resolution": [
          "1024x1024 (2x2 Grids)",
          "1024x2048 (1x4 Grids)",
          "1024x2560 (1x4 Grids)",
          "1024x3072 (1x4 Grids)"
        ]
      }
    },
    "width_1536": {
      "type": "integer",
      "readOnly": "true",
      "description": "Width",
      "visibleIf": {
        "/resolution": [
          "1536x1536 (2x2 Grids)"
        ]
      }
    },
    "height_2048": {
      "type": "integer",
      "readOnly": "true",
      "description": "Height",
      "visibleIf": {
        "/resolution": [
          "2048x2048 (2x2 Grids)",
          "1024x2048 (1x4 Grids)"
        ]
      }
    },
    "height_2560": {
      "type": "integer",
      "readOnly": "true",
      "description": "Height",
      "visibleIf": {
        "/resolution": [
          "1024x2560 (1x4 Grids)"
        ]
      }
    },
    "height_3072": {
      "type": "integer",
      "readOnly": "true",
      "description": "Height",
      "visibleIf": {
        "/resolution": [
          "1024x3072 (1x4 Grids)"
        ]
      }
    },
    "height_1024": {
      "type": "integer",
      "readOnly": "true",
      "description": "Height",
      "visibleIf": {
        "/resolution": [
          "2048x1024 (4x1 Grids)",
          "2560x1024 (4x1 Grids)",
          "3072x1024 (4x1 Grids)",
          "1024x1024 (2x2 Grids)"
        ]
      }
    },
    "height_1536": {
      "type": "integer",
      "readOnly": "true",
      "description": "Height",
      "visibleIf": {
        "/resolution": [
          "1536x1536 (2x2 Grids)"
        ]
      }
    }
  },
  "buttons": [
    {
      "id": "enter",
      "label": "ðŸ¥ª Enter"
    }
  ]
}

=== camenduru/lumina-next-compositional-tost/model.json
{
    "cap1": "Design of a hotel or chalet on the cloud, in the style of light pink, serene oceanic vistas, snailcore, playful machines, 32k UHD, made of rubber, tender depiction of nature",
    "cap2": "Robotic eagle, 8k unreal engine render, wires and gears, photorealistic",
    "cap3": "detailed pen and ink illustration of Boracay Island, by Herge, in the style of tin-tin comics, vibrant colors, detailed, sunny day",
    "cap4": "detailed pen and ink illustration of Boracay Island, by Herge, in the style of tin-tin comics, vibrant colors, detailed, sunny day",
    "neg_cap": "low quality",
    "resolution": "2048x1024 (4x1 Grids)",
    "num_sampling_steps": 30,
    "cfg_scale": 4,
    "solver": "midpoint",
    "t_shift": 4,
    "seed": 0,
    "scaling_method": "Time-aware",
    "scaling_watershed": 0.3,
    "proportional_attn": true,
    "width_2048": 2048,
    "width_2560": 2560,
    "width_3072": 3072,
    "width_1024": 1024,
    "width_1536": 1536,
    "height_2048": 2048,
    "height_2560": 2560,
    "height_3072": 3072,
    "height_1024": 1024,
    "height_1536": 1536
}
